-- MySQL Script generated by MySQL Workbench
-- Fri May  9 14:12:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela` DEFAULT CHARACTER SET utf8 ;
USE `Escuela` ;

-- -----------------------------------------------------
-- Table `Escuela`.`Escuelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Escuelas` (
  `idEscuela` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEscuela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `identificacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Profesores` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL,
  `idDepartamento` INT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`),
  INDEX `idDepartamento_idx` (`idDepartamento` ASC) VISIBLE,
  INDEX `ProfesorUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idDepartamento`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `Escuela`.`Departamentos` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProfesorUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Escuela`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Departamentos` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `idEscuela` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Jefe` INT NULL,
  PRIMARY KEY (`idDepartamento`),
  INDEX `idEscuela_idx` (`idEscuela` ASC) VISIBLE,
  INDEX `Jefeid_idx` (`Jefe` ASC) VISIBLE,
  CONSTRAINT `idEscuela`
    FOREIGN KEY (`idEscuela`)
    REFERENCES `Escuela`.`Escuelas` (`idEscuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Jefeid`
    FOREIGN KEY (`Jefe`)
    REFERENCES `Escuela`.`Profesores` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Cursos` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `idDepartamento` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horaInicial` DATE NOT NULL,
  `horaFinal` DATE NOT NULL,
  `maxEstudiantes` INT NOT NULL,
  `creditos` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `idDepartamento_idx` (`idDepartamento` ASC) VISIBLE,
  CONSTRAINT `DepartamentoDelCurso`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `Escuela`.`Departamentos` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Estudiantes` (
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `grado` INT NOT NULL,
  `promedio` FLOAT NULL,
  PRIMARY KEY (`idEstudiante`),
  INDEX `EstudianteUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `EstudianteUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Escuela`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Evaluaciones` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `idCurso` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `EvaluacionProfesor_idx` (`idProfesor` ASC) VISIBLE,
  INDEX `EvaluacionCurso_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `EvaluacionProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `Escuela`.`Profesores` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EvaluacionCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Escuela`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`cursos_profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`cursos_profesores` (
  `idProfesor` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idProfesor`, `idCurso`),
  INDEX `idCurso_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `idProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `Escuela`.`Profesores` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Escuela`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`cursos_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`cursos_estudiantes` (
  `idEstudiante` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`, `idCurso`),
  INDEX `idCruso_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `idEstudianteDelCurso`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `Escuela`.`Estudiantes` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCursoDelEstudiante`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Escuela`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Administradores` (
  `idAdministrador` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `AdminUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `AdminUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Escuela`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Calificacion` (
  `idCalificacion` INT NOT NULL AUTO_INCREMENT,
  `idEvaluacion` INT NOT NULL,
  `idEstudiante` INT NOT NULL,
  `fechaEntrega` DATE NOT NULL,
  `nota` FLOAT NULL,
  PRIMARY KEY (`idCalificacion`),
  INDEX `CalificacionEvaluacion_idx` (`idEvaluacion` ASC) VISIBLE,
  INDEX `CalificacionEstudiante_idx` (`idEstudiante` ASC) VISIBLE,
  CONSTRAINT `CalificacionEvaluacion`
    FOREIGN KEY (`idEvaluacion`)
    REFERENCES `Escuela`.`Evaluaciones` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CalificacionEstudiante`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `Escuela`.`Estudiantes` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
