/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Usuario;
import GUI.Administrador.PrincipalAdministrador;
import GUI.Estudiante.PrincipalEstudiante;
import GUI.Profesor.PrincipalProfesor;
import middlewares.CurrentSession;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author criskop
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public void verifySession(){
           CurrentSession currentSession = CurrentSession.getInstance();
           
           if(currentSession.getCurrentSessionData() != null){
               Usuario currentUser = currentSession.getCurrentSessionData();
               
               openRoleWindow(currentUser);
               this.dispose();
               System.out.println(currentUser);
           }
    }
    
    public Login() {
        initComponents();
        ApplyFieldsOnlyNumbers();
        verifySession();
    }
    
       private void ApplyFieldsOnlyNumbers(){
    JTextField[] campos = {InputID};

    for (JTextField campo : campos) {
        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Bloquea si NO es un número
                }
            }
        });
    }
}
       
       private void openRoleWindow(Usuario usuario){
               JFrame ventana = switch (usuario.getRol()) {
                case "Estudiantes" -> new PrincipalEstudiante();
                case "Profesores" -> new PrincipalProfesor();
                case "Administradores" -> new PrincipalAdministrador();
                default -> null;
            };

            if (ventana != null) {
                StatusText.setText("¡Inicio de sesión exitoso!");
                StatusText.setForeground(new Color(51,153,0));
                 // Timer que borra el texto después de 3 segundos (3000 ms)
                 new javax.swing.Timer(2000, e -> {
                    ventana.setVisible(true);
                    this.setVisible(false);
                }).start();

                
            } else {
                JOptionPane.showMessageDialog(this, "Rol desconocido: " + usuario.getRol());
            }
       }
       
       private void login(){
           
               //Verificar si el usuario le dio iniciar sesion sin cambiar los inputs xd           
              if(InputID.getText().equals("Documento de Identidad")){
            InputID.setText("");
            InputID.setForeground(new Color(0,0,0));
        }
          
              if(String.valueOf(InputPassword.getPassword()).equals("Password")){
            InputPassword.setText("");
            InputPassword.setForeground(new Color(0,0,0));
        }
      
         //========================================================================
           
           //Si los inputs están vacios
            if (InputID.getText().isEmpty() || String.valueOf(InputPassword.getPassword()).isEmpty()) {
            StatusText.setText("Campos faltantes");

            // Timer que borra el texto después de 3 segundos (3000 ms)
            new javax.swing.Timer(3000, e -> StatusText.setText("")).start();
            return;
        }
        
        //===========================================================================
           //Variables
           var identificacion = Integer.parseInt(InputID.getText());
           String contra = String.valueOf(InputPassword.getPassword());
           
           boolean success = CurrentSession.getInstance().login(identificacion, contra);
           
           
if (success) {
    Usuario usuario = CurrentSession.getInstance().getCurrentSessionData();
    System.out.println("Bienvenido: " + usuario.getNombre());
    
    //===========================================================================
      
           
        
           openRoleWindow(usuario);
} else {
    System.out.println("Login fallido");
      StatusText.setText("Inicio de sesión fallido");

            // Timer que borra el texto después de 3 segundos (3000 ms)
            new javax.swing.Timer(3000, e -> StatusText.setText("")).start();
}
         
           
        
           
           
           
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LeftContainer = new javax.swing.JPanel();
        LeftDownContainer = new javax.swing.JPanel();
        FormContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        InputPassword = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        InputID = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        StatusText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setResizable(false);

        RightContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SistemaEscuela");
        RightContainer.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Logo.png"))); // NOI18N
        RightContainer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo.png"))); // NOI18N
        RightContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 750));

        getContentPane().add(RightContainer, java.awt.BorderLayout.LINE_END);

        LeftContainer.setLayout(new java.awt.BorderLayout());

        LeftDownContainer.setBackground(new java.awt.Color(251, 251, 254));
        LeftDownContainer.setLayout(new java.awt.GridBagLayout());

        FormContainer.setBackground(new java.awt.Color(251, 251, 254));
        FormContainer.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(251, 251, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelBienvenido.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LabelBienvenido.setText("¡Bienvenido!");
        jPanel2.add(LabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 197, 177));
        jLabel1.setText("Inicio de Sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 27, -1, -1));

        FormContainer.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(251, 251, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(251, 251, 254));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(4, 205, 4));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 3));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/lock.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 30));

        InputPassword.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        InputPassword.setForeground(new java.awt.Color(174, 197, 177));
        InputPassword.setText("Password");
        InputPassword.setBorder(null);
        InputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPasswordFocusGained(evt);
            }
        });
        jPanel4.add(InputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, 40));

        jPanel5.setBackground(new java.awt.Color(251, 251, 254));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(4, 205, 4));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 3));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/id.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -2, 30, 30));

        InputID.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        InputID.setForeground(new java.awt.Color(174, 197, 177));
        InputID.setText("Documento de Identidad");
        InputID.setToolTipText("Documento de Identidad");
        InputID.setBorder(null);
        InputID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputIDFocusGained(evt);
            }
        });
        jPanel5.add(InputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 40));

        button1.setBackground(new java.awt.Color(153, 255, 153));
        button1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        button1.setLabel("Iniciar Sesion");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 40));

        jTextField1.setBackground(new java.awt.Color(251, 251, 254));
        jTextField1.setForeground(new java.awt.Color(251, 251, 254));
        jTextField1.setBorder(null);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        StatusText.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        StatusText.setForeground(new java.awt.Color(204, 0, 51));
        StatusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(StatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 300, 20));

        FormContainer.add(jPanel3, java.awt.BorderLayout.CENTER);

        LeftDownContainer.add(FormContainer, new java.awt.GridBagConstraints());

        LeftContainer.add(LeftDownContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(LeftContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputIDFocusGained
        if(InputID.getText().equals("Documento de Identidad")){
            InputID.setText("");
            InputID.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_InputIDFocusGained

    private void InputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPasswordFocusGained
         if(String.valueOf(InputPassword.getPassword()).equals("Password")){
            InputPassword.setText("");
            InputPassword.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_InputPasswordFocusGained

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       login();
        System.out.println("Test");
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormContainer;
    private javax.swing.JTextField InputID;
    private javax.swing.JPasswordField InputPassword;
    private javax.swing.JLabel LabelBienvenido;
    private javax.swing.JPanel LeftContainer;
    private javax.swing.JPanel LeftDownContainer;
    private javax.swing.JPanel RightContainer;
    private javax.swing.JLabel StatusText;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
